# training
conf_id: Crop_res50_plain_20250210 #Crop_Res18_plain_071824
algorithm: Plain
log_dir: Crop
num_epochs: 30
log_interval: 10
parallel: 0

# data
dataset_root: '/media/mo/nvme0n1/MD_up_TT' #./data/imgs
dataset_name: Custom_Crop
# annotation directory (if you have train/val/test splits)
annotation_dir: '/media/mo/nvme0n1/MD_up_TT' #./data/imgs
# data splitting (if you don't have train/val/test splits)
split_path: /media/mo/nvme0n1/MD_up_TT/TT csv files/all_tvt_PW_FT_classification_20250210_182840.csv #./data/imgs/annotation_example.csv
test_size: 0.2
val_size: 0.2
split_data: True
split_type: location # options are: random, location, sequence
# data loading
batch_size: 4 #32
num_workers: 16 #4 #40
# model
num_classes: 42 #2 
model_name: PlainResNetClassifier
num_layers: 50 #18
weights_init: ImageNet

# optim
## feature
lr_feature: 0.01
momentum_feature: 0.9
weight_decay_feature: 0.0005
## classifier
lr_classifier: 0.01
momentum_classifier: 0.9
weight_decay_classifier: 0.0005
## lr_scheduler
step_size: 10
gamma: 0.1

